root = "."
tmp_dir = "tmp"

[build]
  bin = "./main"
  cmd = "go build -o main cmd/go-chatgpt-prompt-splitter/main.go"
  delay = 1000
  exclude_dir = ["build", "docs", "environment", "internal", "scripts", "test", "vendor", "working-files"]
  exclude_file = []
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "js"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
